name: soloforte_backend
description: Backend server para SoloForte App - Feature Flags & Admin API
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  crypto: ^3.0.3
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  http: ^1.1.0
